### ISSUE TITLE
Incorrect placement with different player height

### ISSUE THREAD

**Issue by laugexd** [TheCBProject/CBMultipart#75] opened 2020-01-12 09:59 UTC
When using other mods that change your viewpoints height, the placement of blocks don't align with the guides. The mod seems to place blocks based on where the viewpoint normally is and not where it's currently set to, so mods like morph or vivecraft make it difficult to place blocks, vivecraft being a bigger issue than morph as you can't just turn it off as you can in morph.

If you need anything like a video to better understand my issue please let me know!

**Comment by covers1624** [comment] 2021-11-06 06:50
Sorry for the delay in getting to this issue.

Can you please provide some more information?

What modpack/mod versions?

Can you provide a video displaying this issue?

**Comment by laugexd** [comment] 2021-11-06 08:06
this was so long ago I don't know which mod version this happened in before, but I know it's a bug that has persisted since at least 1.7.10, I also don't have the option of sending a video at this moment, but the steps to reproduce the bugs should be:

1. use morph to change into a chicken
2. try to place a multi part block right on the edge between 2 zones
3. doing this should place it at a different point, because the multipart thinks you are looking at a different place because it only bases the zone placement based on where a normal character's eyes would be, and not where your eyes currently are because you have switched size

I also can't test if this bug even exists anymore, it is possible it was fixed with the addition of crawling, but maybe not.

**Comment by xElementzx** [comment] 2021-11-06 10:18
Seems to have been fixed in the 1.12 Lifecycle, i am unable to reproduce this issue.
If you are able to reproduce it with the current versions of CBMultipart/Forge Multipart and CCL for 1.16 feel free to reopen

**Closed by xElementzx** 2021-11-06 10:18 UTC
Labels: waiting
